export const PLANS = [
  {
    id: 'free',
    badge: '免费',
    name: '草稿本',
    tagline: '先把「计划 → 任务 → 练习」跑通，不急着付费。',
    priceMonth: '0',
    unitMonth: '元 / 永久',
    noteMonth: '随时可换本，进度保留',
    priceYear: '0',
    unitYear: '元 / 永久',
    noteYear: '随时可换本，进度保留',
    features: [
      '1 个进行中的生活微目标计划',
      '每周 3 张核心场景任务卡',
      '每月 8 次 AI 陪练（先独立稿 · 讲解→练习→追问）',
      '独立输出存练习（最近 14 天）',
      '轻量周复盘清单',
    ],
    omit: '暂不含语音陪练与毕业任务',
    cta: '开始使用草稿本',
    featured: false,
    quiet: true,
    ghost: true,
  },
  {
    id: 'daily',
    badge: '多数人选',
    name: '日常本',
    tagline: '日常提升的主力本：计划更稳，痕迹留得更全。',
    priceMonth: '58',
    unitMonth: '元 / 月',
    noteMonth: '年付 ¥468 · 约合 ¥39 / 月',
    priceYear: '468',
    unitYear: '元 / 年',
    noteYear: '约合 ¥39 / 月 · 含 4 个月坚持奖励',
    features: [
      '多目标计划切换 · 今日计划提醒',
      '旅行 / 看剧 / 聊天 / 兴趣阅读场景任务卡',
      '每月 40 次 AI 陪练（先独立稿 · 禁整段改写）',
      '练习完整历史 · 月度前后对比',
      '周复盘：完成 · 质量 · 保持 · 迁移',
      '每月 8 次语音陪练',
    ],
    omit: null,
    cta: '选择日常本',
    featured: true,
    quiet: false,
    ghost: false,
  },
  {
    id: 'deep',
    badge: '深练',
    name: '深练本',
    tagline: '把对比拉长，把场景练回真实生活。',
    priceMonth: '108',
    unitMonth: '元 / 月',
    noteMonth: '年付 ¥888 · 约合 ¥74 / 月',
    priceYear: '888',
    unitYear: '元 / 年',
    noteYear: '约合 ¥74 / 月 · 含 4 个月坚持奖励',
    features: [
      '日常本全部能力',
      '每月 100 次 AI 陪练（边界同上）',
      '语音陪练更宽裕（约 30 次 / 月）',
      '毕业任务：把场景用回真实生活',
      '练习跨季对比 · 可导出笔记',
    ],
    omit: '同样不做整段代写',
    cta: '选择深练本',
    featured: false,
    quiet: true,
    ghost: true,
  },
] as const

export type PlanId = (typeof PLANS)[number]['id']
